changelog:
  categories:
    - title: '🛠 Maintenance'
      label:
        - maintenance
    - title: '💡 New Features'
      labels:
        - enhancement
    - title: '😬 Breaking'
      labels:
        - breaking
    - title: '🙈 Bug Fixes'
      label:
        - fix
    - title: '📖 Documentation'
      label:
        - doc
