name: check-labels

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - unlabeled

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# default to 0 permissions
# (job-level overrides add the minimal permissions needed)
permissions:
  contents: none

jobs:
  check:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: read
      issues: read
      pull-requests: read
    steps:
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
        with:
          mode: exactly
          add_comment: false
          count: 1
          # this should match release-drafter.yml
          labels: |
            breaking
            doc
            enhancement
            fix
            maintenance
