---
name: manual-run

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Name of a package on PyPI'
        required: true
        type: string

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# default to 0 permissions
# (job-level overrides add the minimal permissions needed)
permissions:
  contents: none

jobs:
  check-package:
    name: check-package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: check '${{ inputs.package_name }}'
        env:
          INPUT_PACKAGE_NAME: ${{ inputs.package_name }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            llvm
          python -m pip install \
            pipx
          make install
          mkdir -p ./tmp-dir
          python bin/get-pypi-files.py\
            "${INPUT_PACKAGE_NAME}" \
            ./tmp-dir
          pydistcheck ./tmp-dir/*
