---
name: smoke-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # run every Wednesday at midnight UTC
  schedule:
    - cron: '0 0 * * 3'

# automatically cancel in-progress builds if another commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# default to 0 permissions
# (job-level overrides add the minimal permissions needed)
permissions:
  contents: none

jobs:
  test:
    name: smoke-tests (${{ matrix.os }}, ${{ matrix.python_version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python_version: '3.9'
          - os: ubuntu-latest
            python_version: '3.13'
          - os: windows-latest
            python_version: '3.12'
    permissions:
      contents: read
    steps:
      - name: check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install extra tools on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            llvm
      - name: run tests
        shell: bash
        env:
          # ensure 'pipx' uses the Python interpreter set up by 'actions/setup-python'
          PIPX_HOME: ${{ runner.temp }}/pipx
          PIPX_BIN_DIR: ${{ runner.temp }}/pipx/bin
        run: |
          export PATH="${PIPX_BIN_DIR}:${PATH}"
          python -m pip install \
              pipx \
              requests
          make install
          make smoke-tests
  all-smoke-tests-successful:
    if: always()
    runs-on: ubuntu-slim
    needs:
      - test
    permissions:
      statuses: read
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
